### ISSUE TITLE
Ez Boss Cheese 1: stand in the opposite corner and the circular bullet attack wont hit you

### ISSUE THREAD

**Issue by jkcarney** [BrothersStudio/bottles-defy-gravity#19]
So whatever corner the boss fires his circular bullet attack from, stand in the opposite corner from him as far as you can go and stand still. The bullets will not hit you which allows you to easily just shoot him with the gun. Tested for every corner of the room.

**Comment by pwcarney** [comment]
I made the player hitbox bigger as part of other stuff so this came out in the wash, done, no problem ez pz
