### ISSUE TITLE
Ez Boss Cheese 2: Stand next to boss with sword and spam click

### ISSUE THREAD

**Issue by jkcarney** [BrothersStudio/bottles-defy-gravity#20]
If the boss is using his circular attack and you stand right next to him and spam sword attack, all the bullets will be reflected and your attack will still go through, damaging the boss severely. Works on phase 1 and 2.

**Comment by pwcarney** [comment]
There's some weird incidental bugs here like how the bullets seem to bunch up, weird edge case I'm nooot gonna address. Working on this now I have an idea

**Comment by pwcarney** [comment]
Okay, you can only slice one bullet per sword swing
