### ISSUE TITLE
Tutorial Adjustments

### ISSUE THREAD

**Issue by christophercarney** [BrothersStudio/bottles-defy-gravity#38]
All or any of these:

- [x] Move blue enemy further back in the room
- [x] Put a static laser in the second tutorial room
- [x] Some way to recoup any damage incurred in the tutorial rooms
- [ ] After first tutorial go-through subsequent times should allow player to continue without completion (i.e. doors always open)

**Comment by pwcarney** [comment]
I don't really see the need to keep the doors open since it takes very little time, everything else is addressed
