### ISSUE TITLE
Adjust slash mechanic

### ISSUE THREAD

**Issue by christophercarney** [BrothersStudio/bottles-defy-gravity#41]
>  This one is kind of hard to articulate but if your player is facing "Left" and you slash while your mouse is facing "Up" the PC slashes Up and not left, basically seems like slash direction is based on where the mouse is pointing not the direction the player is facing, makes combat slightly frustrating and I think it's the opposite of what the user is expecting, slashing should happen in the direction the user is already facing and gun should shoot where the mouse is pointing, another possible fix could be the Arc of the slash could be in a full 'C' shape around the PC, i.e. they hit everything that isn't behind them <-- The more I play the more adamant I am that the slash should be based on player direction not mouse location

- [ ] Slightly tweak length and arc (make them both longer)
- [ ] F stop should be as low as possible to provide uncompromising combat flow

**Comment by krcarney** [comment]
Done!
